from enum import StrEnum


class GlobalDeduplicationErrorCode(StrEnum):
    INPUT_MANIFEST_NOT_FOUND = "INPUT_MANIFEST_NOT_FOUND"
    INPUT_MANIFEST_ACCESS_FAILED = "INPUT_MANIFEST_ACCESS_FAILED"
    INPUT_MANIFEST_TOO_LARGE = "INPUT_MANIFEST_TOO_LARGE"
    INVALID_INPUT_MANIFEST = "INVALID_INPUT_MANIFEST"
    EMPTY_DOCUMENT_LIST = "EMPTY_DOCUMENT_LIST"
    DUPLICATE_FILE_ID = "DUPLICATE_FILE_ID"
    DOCUMENT_PATH_NOT_ALLOWED = "DOCUMENT_PATH_NOT_ALLOWED"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_READ_FAILED = "DOCUMENT_READ_FAILED"
    DOCUMENT_TOO_LARGE = "DOCUMENT_TOO_LARGE"
    BATCH_TOO_LARGE = "BATCH_TOO_LARGE"
    UNSUPPORTED_DOCUMENT_FORMAT = "UNSUPPORTED_DOCUMENT_FORMAT"
    DOCUMENT_DECODE_FAILED = "DOCUMENT_DECODE_FAILED"
    STAGING_CREATE_FAILED = "STAGING_CREATE_FAILED"
    STAGING_WRITE_FAILED = "STAGING_WRITE_FAILED"
    STAGING_READ_FAILED = "STAGING_READ_FAILED"
    STAGING_INTEGRITY_FAILED = "STAGING_INTEGRITY_FAILED"
    PROCESSOR_PROFILE_NOT_SUPPORTED = "PROCESSOR_PROFILE_NOT_SUPPORTED"
    PROCESSOR_REQUEST_REJECTED = "PROCESSOR_REQUEST_REJECTED"
    PROCESSOR_IDEMPOTENCY_CONFLICT = "PROCESSOR_IDEMPOTENCY_CONFLICT"
    PROCESSOR_SUBMISSION_FAILED = "PROCESSOR_SUBMISSION_FAILED"
    PROCESSOR_SUBMISSION_UNCERTAIN = "PROCESSOR_SUBMISSION_UNCERTAIN"
    PROCESSOR_UNAVAILABLE = "PROCESSOR_UNAVAILABLE"
    INVALID_PROCESSOR_RESPONSE = "INVALID_PROCESSOR_RESPONSE"
    PROCESSOR_JOB_NOT_FOUND = "PROCESSOR_JOB_NOT_FOUND"
    PROCESSOR_POLL_FAILED = "PROCESSOR_POLL_FAILED"
    PROCESSOR_TIMEOUT = "PROCESSOR_TIMEOUT"
    PROCESSOR_FAILED = "PROCESSOR_FAILED"
    PROCESSOR_CANCELLED = "PROCESSOR_CANCELLED"
    INVALID_PROCESSOR_OUTPUT = "INVALID_PROCESSOR_OUTPUT"
    OUTPUT_PATH_NOT_ALLOWED = "OUTPUT_PATH_NOT_ALLOWED"
    OUTPUT_CONFLICT = "OUTPUT_CONFLICT"
    OUTPUT_WRITE_FAILED = "OUTPUT_WRITE_FAILED"
    OUTPUT_INTEGRITY_FAILED = "OUTPUT_INTEGRITY_FAILED"
    QUEUE_SUBMISSION_FAILED = "QUEUE_SUBMISSION_FAILED"
    DATABASE_ERROR = "DATABASE_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class GlobalDeduplicationProcessingError(RuntimeError):
    def __init__(
        self,
        code: GlobalDeduplicationErrorCode,
        safe_message: str,
        *,
        transient: bool = False,
    ) -> None:
        super().__init__(f"{code}: {safe_message}")
        self.code = code
        self.safe_message = safe_message
        self.transient = transient
